version: '3.7'

services:
  looks-like-tests:
    container_name: backend_container
    build: .
    ports:
      - "8080:8080"
    networks:
      - postgres
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/looksliketests
      - JDBC_DATABASE_USERNAME=${POSTGRES_USER:-postgres}
      - JDBC_DATABASE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on:
      - "postgres"
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: looksliketests
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - "postgres"

networks:
  postgres:
    driver: bridge

volumes:
  looks-like-tests:
  postgres:
  pgadmin: