CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    username text,
    password text,
    first_name text,
    last_name text,
    middle_name text,
    email text,
    phone text,
    activated boolean,
    CONSTRAINT user_id_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS auth.user_authority
(
    user_id bigint NOT NULL,
    name text NOT NULL,
    CONSTRAINT user_authority_pkey PRIMARY KEY (user_id, name),
    CONSTRAINT user_authority_user_fk FOREIGN KEY (user_id)
        REFERENCES auth.user (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

