CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    username text,
    password text,
    first_name text,
    last_name text,
    email text,
    activated boolean,
    CONSTRAINT user_id_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS auth.authority
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    name text,
    CONSTRAINT authority_id_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS auth.user_authority
(
    user_id bigint NOT NULL,
    authority_id bigint NOT NULL,
    CONSTRAINT user_authority_pkey PRIMARY KEY (user_id, authority_id),
    CONSTRAINT user_authority_user_fk FOREIGN KEY (user_id)
        REFERENCES auth.user (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT user_authority_authority_fk FOREIGN KEY (authority_id)
        REFERENCES auth.authority (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

