CREATE TABLE main.student_to_teacher_assignation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    student_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    date_created timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT student_to_teacher_assignation_id_pkey PRIMARY KEY (id),
    CONSTRAINT student_to_teacher_assignation_student_id_fk FOREIGN KEY (student_id)
        REFERENCES auth."user" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT student_to_teacher_assignation_teacher_id_fk FOREIGN KEY (teacher_id)
        REFERENCES auth."user" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
