CREATE TABLE main.test_progress
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    test_id bigint NOT NULL,
    user_id bigint NOT NULL,
    date_started timestamp with time zone NOT NULL,
    date_finished timestamp with time zone,
    CONSTRAINT test_progress_id_pkey PRIMARY KEY (id),
    CONSTRAINT test_progress_test_id_test_fk FOREIGN KEY (test_id)
        REFERENCES main.test (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT test_progress_user_id_user_fk FOREIGN KEY (user_id)
        REFERENCES auth."user" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);