CREATE TABLE main.test_answer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    test_progress_id bigint NOT NULL,
    question_id bigint NOT NULL,
    option_id bigint,
    text_answer text,
    CONSTRAINT test_answer_id_pkey PRIMARY KEY (id),
    CONSTRAINT test_answer_unique UNIQUE (test_progress_id, question_id, option_id),
    CONSTRAINT test_answer_test_progress_id_test_progress_fk FOREIGN KEY (test_progress_id)
        REFERENCES main.test_progress (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT test_answer_question_id_question_fk FOREIGN KEY (question_id)
        REFERENCES main.question (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT test_answer_option_id_option_fk FOREIGN KEY (option_id)
        REFERENCES main.option (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);